# Generated by Django 4.2.5 on 2023-11-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='DBrEpclX4wI', max_length=256, verbose_name='パスワードリセットトークン')),
                ('is_used', models.BooleanField(verbose_name='使用済みフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('expired_at', models.DateTimeField(verbose_name='トークン有効期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
