# Generated by Django 4.2.5 on 2023-11-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='使用済みフラグ'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='rlwCzeVh7l4qCDOP8bN_c2Cgf6qZ4AjmVVcHy134vtPZNF9rIQIfO6TFUMkgJRVWU5XBwy8CfoDTo89Cl8fKKzHbt0XKMbHYbZFOJMCuDvpVwXzO79My-Fu2rQT7VK-AHDIopbnGDopCf0km5Z3lv16vucu758YrdZUIddVRS54', max_length=256, verbose_name='パスワードリセットトークン'),
        ),
    ]
