# Generated by Django 4.2.5 on 2023-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='ysAociLWPVhRMxPP6W4pYQZ0ndy0PqrH-Qu4JU5JP1Q', max_length=256, verbose_name='パスワードリセットトークン'),
        ),
    ]
