# Generated by Django 4.2.5 on 2023-12-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='sG83JqowRjFyoxJj7gjrL5VjRl2Hih4jo-nr5clJf6Y', max_length=256, verbose_name='パスワードリセットトークン'),
        ),
    ]
