# Generated by Django 4.2.5 on 2023-11-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='組織名')),
                ('post_code', models.CharField(max_length=20, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=256, verbose_name='都道府県')),
                ('city', models.CharField(max_length=56, verbose_name='市区町村')),
                ('address', models.CharField(max_length=256, verbose_name='住所(市区町村以下)')),
                ('tel_number', models.CharField(max_length=20, verbose_name='代表電話番号')),
                ('manager_name', models.CharField(max_length=256, verbose_name='担当者名')),
                ('plans', models.IntegerField(verbose_name='利用プランID')),
                ('status', models.IntegerField(choices=[(1, 'アクティブ'), (2, '非アクティブ'), (99, '利用停止')], default=2, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
                'db_table_comment': '組織テーブル',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='招待日')),
                ('joined_at', models.DateTimeField(null=True, verbose_name='参加日')),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, '招待中（参加待ち）'), (99, '停止')], verbose_name='ステータス')),
                ('organization', models.ForeignKey(db_comment='所属組織のID', on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='所属組織')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メンバー',
                'verbose_name_plural': 'メンバー',
                'db_table': 'organization_users',
                'db_table_comment': '組織とユーザーの中間テーブル',
                'ordering': ('-organization', 'status'),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='organization.OrganizationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
