# Generated by Django 4.2.5 on 2023-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.IntegerField(choices=[(1, 'アクティブ'), (2, '非アクティブ'), (99, '利用停止')], default=2, verbose_name='ステータス'),
        ),
    ]
