# Generated by Django 4.2.5 on 2023-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plans',
            field=models.IntegerField(choices=[(1, '無料プラン'), (2, 'スタンダード'), (3, 'エンタープライズ')], verbose_name='利用プランID'),
        ),
    ]
