# Generated by Django 4.2.5 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='role',
            field=models.IntegerField(choices=[(1, '管理者'), (2, '一般ユーザー'), (3, '閲覧者')], default=1, verbose_name='ロール'),
            preserve_default=False,
        ),
    ]
